version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.5
  node: circleci/node@1.1.6

jobs:
  build-1:
    executor:
      name: node/default

    steps:
      - checkout

      - node/with-cache:
          steps:
            - run: "command -v meteor >/dev/null 2>&1 || (npm install --prefix=$HOME/.local -g meteor && echo 'export PATH=$HOME/.meteor:$PATH' >> $BASH_ENV) && npm install"
            - run: meteor npm run test

      - coveralls/upload:
          parallel: true
          flag_name: meteor mocha coverage
          verbose: true

  done:
    executor:
      name: node/default

    steps:
      - coveralls/upload:
          parallel_finished: true

workflows:
  test_parallel_then_upload:
    jobs:
      - build-1
      - done:
          requires: [build-1]